# Generated by Django 4.1.7 on 2023-03-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("company_name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("invoice_currency", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=5, unique=True)),
                (
                    "invoiced_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("invoice_date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "invoiced_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ota_app.user"
                    ),
                ),
            ],
        ),
    ]
